# Generated by Django 5.2 on 2025-07-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_review_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='review',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'معلق'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='حالة الموافقة'),
        ),
    ]
