# Generated by Django 5.2 on 2025-07-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_is_approved_review_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
    ]
